name: sfi

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python = 3.10
  - pytorch::pytorch-cuda = 11.6
  - pytorch::pytorch = 1.13
  - pytorch::torchaudio
  - pip
  - pip:
    - pandas
    - simplejson
    - pyyaml
    - coloredlogs
    - scipy
    - librosa
    - musdb
    - museval
    - hydra-core==0.11.3
    - Cython
    - tqdm
